version: '3.8'

services:
  neo4j:
    image: neo4j:4.4-community
    container_name: neo4j
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - ../data/neo4j/data:/data
      - ../data/neo4j/logs:/logs
      - ../data/neo4j/plugins:/var/lib/neo4j/plugins
    networks:
      - neo4j-network
    restart: no

  app:
    image: neo4j_client
    container_name: python-app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=Neo4j
    networks:
      - neo4j-network
    restart: no

networks:
  neo4j-network:
    driver: bridge