global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'neo4j'
    scrape_interval: 5s

    static_configs:
      - targets: ['neo4j:2004']

    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
