version: '3.8'

services:
  falkordb:
    image: falkordb/falkordb:edge
    container_name: falkordb
    ports:
      - "6379:6379"
    volumes:
      - ../data/falkor:/data
    networks:
      - falkordb-network
  
  python-app:
    image: db_profiler
    container_name: python-app
    depends_on:
      - falkordb
    networks:
      - falkordb-network
    
networks:
  falkordb-network:
    driver: bridge