global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'arangodb'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: '/_admin/metrics'
    static_configs:
      - targets: ['arangodb:8529']
